version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: infra/Dockerfile
    env_file:
      - .env
    volumes:
      - sqlite_data:/data
    restart: unless-stopped
    networks:
      - edcx_network

  memcached:
    image: memcached:latest
    restart: unless-stopped
    networks:
      - edcx_network

networks:
  edcx_network:
    external: true

volumes:
  sqlite_data:
