version: "3.9"

services:
  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    env_file:
      - ../.env
    environment:
      DATA_DIR: /data
      DJANGO_SETTINGS_MODULE: config.prod_settings
    volumes:
      - xcmagg_db:/data
    restart: unless-stopped
    networks:
      - racefeed_network

  memcached:
    image: memcached:latest
    restart: unless-stopped
    networks:
      - racefeed_network

networks:
  racefeed_network:
    name: racefeed_network

volumes:
  xcmagg_db:
