# Generated by Django 6.0.1 on 2026-01-27 17:51

import django.db.models.deletion
import nodes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0005_alter_node_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('node', models.OneToOneField(limit_choices_to={'kind': 'user_profile'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='nodes.node')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(nodes.models.NodeBoundModel, models.Model),
        ),
    ]
