# Generated by Django 6.0.1 on 2026-01-20 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('post', 'Post'), ('catalog_item', 'Catalog Item'), ('inventory_item', 'Inventory Item'), ('category', 'Category'), ('manufacturer', 'Manufacturer'), ('comment', 'Comment')], db_index=True, max_length=32)),
                ('shortcode', models.CharField(blank=True, db_index=True, editable=False, max_length=16, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], db_index=True, default='public', max_length=16)),
                ('votes_allowed', models.BooleanField(default=True)),
                ('comments_allowed', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nodes.node')),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'visibility'], name='nodes_node_kind_79d852_idx')],
            },
        ),
    ]
