# Generated by Django 6.0.1 on 2026-01-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='posts_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(choices=[('post', 'Post'), ('catalog_item', 'Catalog'), ('inventory_item', 'Inventory'), ('category', 'Category'), ('manufacturer', 'Manufacturer'), ('comment', 'Comment')], db_index=True, max_length=32),
        ),
    ]
