# Generated by Django 6.0.1 on 2026-01-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_node_posts_allowed_alter_node_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
