# Generated by Django 6.0.1 on 2026-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_node_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
