# Generated by Django 6.0.1 on 2026-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_node_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(choices=[('post', 'Post'), ('catalog_item', 'Catalog'), ('inventory_item', 'Inventory'), ('category', 'Category'), ('manufacturer', 'Manufacturer'), ('comment', 'Comment'), ('user_profile', 'UserProfile')], db_index=True, max_length=32),
        ),
    ]
