# Generated by Django 6.0.1 on 2026-02-02 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_alter_node_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'user_profile')), fields=('owner', 'kind'), name='unique_user_profile_node'),
        ),
    ]
