# Generated by Django 6.0.1 on 2026-01-20 18:10

import django.db.models.deletion
import nodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('node', models.OneToOneField(limit_choices_to={'kind': 'category'}, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='nodes.node')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
            bases=(nodes.models.NodeBoundModel, models.Model),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('node', models.OneToOneField(limit_choices_to={'kind': 'manufacturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='nodes.node')),
            ],
            bases=(nodes.models.NodeBoundModel, models.Model),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_listed', models.BooleanField(default=False)),
                ('accepts_trade', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_node', models.ForeignKey(blank=True, limit_choices_to={'kind': 'catalog_item'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ugc_items', to='nodes.node')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='nodes.node')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.manufacturer')),
            ],
            bases=(nodes.models.NodeBoundModel, models.Model),
        ),
        migrations.CreateModel(
            name='RetailerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('is_affiliate', models.BooleanField(default=False)),
                ('promo_code', models.CharField(blank=True, max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_links', to='catalog.item')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
