# Generated by Django 6.0.1 on 2026-01-25 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_item_category_alter_item_description_and_more'),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='node',
            field=models.OneToOneField(limit_choices_to={'kind__in': ['catalog_item', 'inventory_item']}, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='nodes.node'),
        ),
    ]
