# Generated by Django 6.0.1 on 2026-02-02 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_item_node'),
        ('nodes', '0006_node_unique_user_profile_node'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailerlink',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='retailerlink',
            name='item',
        ),
        migrations.AddField(
            model_name='retailerlink',
            name='label',
            field=models.CharField(default='Watch', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailerlink',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_links', to='nodes.node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailerlink',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='retailerlink',
            name='promo_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='retailerlink',
            name='text',
            field=models.CharField(max_length=64),
        ),
    ]
