# Generated by Django 6.0.6 on 2026-06-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_retailerlink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailerlink',
            name='label',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
