# Generated by Django 6.0.6 on 2026-06-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_retailerlink_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='audience',
            field=models.CharField(blank=True, choices=[('bike', 'For the Bike'), ('rider', 'For the Rider')], max_length=16),
        ),
        migrations.AddField(
            model_name='category',
            name='durability',
            field=models.CharField(blank=True, choices=[('durable', 'Durable'), ('consumable', 'Consumable')], max_length=16),
        ),
    ]
