# Generated by Django 6.0.1 on 2026-01-20 18:10

import django.db.models.deletion
import django.utils.timezone
import nodes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('thread', models.CharField(default='', editable=False, max_length=64)),
                ('body', models.TextField()),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='nodes.node')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='engagement.post')),
            ],
            options={
                'indexes': [models.Index(fields=['node'], name='engagement__node_id_7a39b2_idx')],
            },
            bases=(nodes.models.NodeBoundModel, models.Model),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Up'), (-1, 'Down')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='nodes.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['node'], name='engagement__node_id_e8867b_idx')],
                'unique_together': {('node', 'owner')},
            },
        ),
    ]
