# Generated by Django 6.0.1 on 2026-01-25 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='node',
            field=models.OneToOneField(limit_choices_to={'kind__in': ['post', 'comment']}, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='nodes.node'),
        ),
    ]
