# Generated by Django 6.0.1 on 2026-01-25 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('c', 'Created'), ('s', 'Success'), ('f', 'Failure'), ('e', 'Expired')], db_index=True, max_length=1)),
                ('scope', models.CharField(blank=True, choices=[('e', 'Email'), ('q', 'QR Code')], max_length=1, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created'], name='magiclink_l_user_id_3e54a3_idx'), models.Index(fields=['event_type', '-created'], name='magiclink_l_event_t_1f4d55_idx')],
            },
        ),
    ]
