# Generated by Django 6.0.1 on 2026-01-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magiclink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('event_type', models.CharField(choices=[('c', 'Created'), ('s', 'Success'), ('f', 'Failure'), ('e', 'Expired')], db_index=True, max_length=1)),
                ('scope', models.CharField(blank=True, choices=[('e', 'Email'), ('q', 'QR Code')], max_length=1, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='loginevent',
            name='magiclink_l_user_id_3e54a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginevent',
            name='magiclink_l_event_t_1f4d55_idx',
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['email', '-created'], name='magiclink_a_email_c990ff_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_type', '-created'], name='magiclink_a_event_t_09be62_idx'),
        ),
        migrations.DeleteModel(
            name='LoginEvent',
        ),
    ]
