# Generated by Django 6.0.1 on 2026-01-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magiclink', '0002_auditevent_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditevent',
            name='magiclink_a_email_c990ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditevent',
            name='magiclink_a_event_t_09be62_idx',
        ),
        migrations.RenameField(
            model_name='auditevent',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['email', '-timestamp'], name='magiclink_a_email_184d63_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_type', '-timestamp'], name='magiclink_a_event_t_535aa0_idx'),
        ),
    ]
