# Generated by Django 6.0.6 on 2026-06-18 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=2000)),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('cloak', models.BooleanField(default=True)),
                ('rel_sponsored', models.BooleanField(default=False)),
                ('rel_nofollow', models.BooleanField(default=True)),
                ('rel_ugc', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.CharField(blank=True, max_length=512)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_clicks', to=settings.AUTH_USER_MODEL)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='linkcloak.link')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['link', 'created_at'], name='linkcloak_c_link_id_21826a_idx')],
            },
        ),
    ]
