# Generated by Django 6.0.6 on 2026-06-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkcloak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='link',
            name='utm_content',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='link',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='link',
            name='utm_source',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='link',
            name='utm_term',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
